### ISSUE TITLE
Strech background image

### ISSUE THREAD

**Issue by Aliux02** [Aliux02/404#1]
Istempti background per visa viewporta

**Comment by Aliux02** [comment]
Istempti ekrana per viewporta

**Comment by yashasvimisra2798** [comment]
have u tried using an SVG background? because PNG would tend to preserve its aspect ratio

**Comment by Aliux02** [comment]
Hello. I'm learning, just started two weeks ago. It's my... i don't know even how to express it... maybe... it's my try to make something. Thanks for your tips :)

**Comment by Aliux02** [comment]
I don't even know yet how to assign someone else but me

**Comment by yashasvimisra2798** [comment]
#2 img is now responsive but couldn't get rid of those white spaces

**Comment by yashasvimisra2798** [comment]
If merged Pull Request has solved the problems then consider closing the issue, else mention if there is any problem.

**Comment by Aliux02** [comment]
Thanks. I Will try to close it tomorrow. Today I'm having a lecture. Thank you for your work.
